USE [Velo]

CREATE TABLE ACCOUNT (
	ID_User CHAR(10) PRIMARY KEY,
	Account_ID VARCHAR(50),
	Pass VARCHAR(50),
	Name NVARCHAR(50),
	DateOfBirth DATE,
	Gender NVARCHAR(50),
	Nationality NVARCHAR(50),
	Hobby NVARCHAR(50),
	Email VARCHAR(50),
	isVip BIT NOT NULL DEFAULT (0)
)

CREATE TABLE PHOTO(
	Photo_ID CHAR(10) PRIMARY KEY,
	Link NVARCHAR(500) NOT NULL DEFAULT ('/assets/img/user-icon.png'),
	Time_added DATETIME,
	ID_User CHAR(10) REFERENCES ACCOUNT(ID_User),
	isAvatar BIT
)

CREATE TABLE CONVERSATION(
	Conversation_ID CHAR(10) PRIMARY KEY
)

CREATE TABLE CONVERSATION_DETAIL(
	Conversation_ID CHAR(10) REFERENCES CONVERSATION(Conversation_ID),
	ID_User CHAR(10) REFERENCES ACCOUNT(ID_User),
	Name NVARCHAR(50),
	PRIMARY KEY(Conversation_ID, ID_User)
)

CREATE TABLE MESSAGE(
	Message_ID CHAR(10) PRIMARY KEY,
	Message_text NVARCHAR(1000),
	Time_sent DATETIME,
	User_ID_Sent CHAR(10) REFERENCES ACCOUNT(ID_USER),
	Conversation_ID CHAR(10) REFERENCES CONVERSATION(Conversation_ID)
)

CREATE TABLE RELATION(
	Rela_ID CHAR(10) PRIMARY KEY,
	Account_ID_Sent CHAR(10) REFERENCES ACCOUNT(ID_User),
	Account_ID_received CHAR(10) REFERENCES ACCOUNT(ID_User)
)

GO
CREATE proc [dbo].[getConversation] @sender_id char(10), @receiver_id char(10) as
begin
	select chat1.Conversation_ID from CONVERSATION_DETAIL as chat1, CONVERSATION_DETAIL as chat2
	where chat1.Conversation_ID = chat2.Conversation_ID and chat2.ID_User = @receiver_id and chat1.ID_User = @sender_id
end

--DROP TABLE CONVERSATION_DETAIL
--DROP TABLE RELATION
--DROP TABLE PHOTO
--DROP TABLE MESSAGE
--DROP TABLE ACCOUNT
--DROP TABLE CONVERSATION